// Owner-requested locations from the 29 September 2026 screenshot.
// Scenarios are enquiry guidance, never claims about local jobs or housing stock.
export const areaAdditions = [
  { en: 'Sydney CBD & Inner City', zh: '悉尼市区与内城', names: ['Haymarket','Ultimo','Waterloo','Zetland'] },
  { en: 'Inner West', zh: '内西区', names: ['Rhodes','Strathfield'] },
  { en: 'Eastern Suburbs', zh: '东区', names: ['Kingsford'] },
  { en: 'Ryde & North West', zh: 'Ryde与西北', names: ['Marsfield'] },
  { en: 'Parramatta & Surrounds', zh: 'Parramatta及周边', names: ['Auburn'] },
  { en: 'South Western Sydney', zh: '西南悉尼', names: ['Campsie'] },
  { en: 'Wollondilly', zh: 'Wollondilly 地区', names: ['Appin'] },
  { en: 'Central Coast', zh: '中央海岸', names: ['Berkeley Vale','Killarney Vale','The Entrance'] },
  { en: 'Illawarra & Wollongong', zh: 'Illawarra 与 Wollongong 地区', names: ['Fairy Meadow','Gwynneville','Mount Ousley','North Wollongong','Shellharbour','Wollongong'] },
];

// name, postcode, service, bilingual brief, bilingual question, detail and comparison.
const rows = [
  ['Appin','2560','S16',
    'Planning timber sleeper edging? Include the border length, corners and the ground level on each side, not only the number of sleepers.', '计划安装木 sleeper 边框？请说明总长度、转角和两侧地面高低，而不只报 sleeper 数量。',
    'Will the timber separate a garden bed or retain a change in level?', '木材用于分隔花坛，还是挡住地面高低差？',
    'A low garden border and timber holding back soil need different assessment. Show how the proposed line meets paths and existing fences, and where water runs. Include the route for long timber and old material removal. Agree the support, ground preparation and any drainage work before buying sleepers.',
    '低矮花园边框与需要挡土的木材，评估重点不同。请拍出计划走向与步道、围栏的连接以及水流位置，并说明长木材进出和旧料清运通道。采购 sleeper 前，先确认支撑、地面准备及可能需要的排水工作，避免把简单边框报价当作完整挡土工程。',
    'Compare replacing the failed lengths with resetting a continuous edge. List retained timber, new supports, ground preparation and disposal separately; painting is not a remedy for unstable timber.',
    '比较只换坏木料与重新整理连续边框，分别列出保留木材、新支撑、地面准备及清运。刷漆不能代替解决木材不稳的问题。'],
  ['Auburn','2144','S02',
    'For several timber repairs at one property, separate the entrance door, internal doors and cupboards before requesting a combined quote.', '同一物业有多项木作维修时，请先分开入户门、室内门与柜门，再咨询合并报价。',
    'Which door needs security, alignment or timber repair first?', '哪扇门要先处理锁闭、对位或木材损坏？',
    'Number the doors in your photos and explain which entrance must remain secure. A frame repair, hinge adjustment and cabinet hinge replacement are different tasks even when they are at the same property. Include the person arranging access and any agreed work window so the quote covers the right rooms and components.',
    '照片中的门可逐一编号，并指出必须保持可锁闭的入口。门框修木、门铰链调整与柜门铰链更换虽然在同一物业，也属于不同工作。请注明谁安排进入及可施工时段，让报价对应正确房间和构件，不因合并询价而漏掉表面收尾或五金范围。',
    'Ask for an itemised repair list before choosing a combined visit. Keep compatible lock hardware, timber repairs and surface finishing on separate lines so optional work remains a choice.',
    '先索取分项维修清单，再决定合并安排；相容锁具、修木及表面收尾分别列出，方便选择优先工作。'],
  ['Berkeley Vale','2261','S05',
    'If fence repairs meet a garden edge, photograph both the fence supports and the timber at soil level; they may need separate work.', '围栏维修位置连着花园边框时，请同时拍围栏支撑与贴近土壤的木材，两者可能需要分别处理。',
    'Can the fence be repaired without disturbing the garden border?', '维修围栏时能保留原有花园边框吗？',
    'Mark the loose fence spans and show whether soil, edging or planting limits access to the posts. Tell us which garden timber you want retained. Work on a fence post does not automatically include resetting sleeper edging, shifting soil or restoring planting; make those choices clear before the scope is priced.',
    '请标出松动跨段，并说明泥土、木边框或种植是否挡住柱脚通道，哪些花园木材希望保留。修围栏柱不默认包含重设 sleeper、搬土或恢复种植。这些选择要在报价前说明，同时确认两侧进入方式和拆下旧木材如何搬出，避免施工范围不清楚。',
    'Compare a fence-only repair with a combined fence-and-edging scope. Keep the new timber lengths, post work and garden reinstatement distinct in the quotation.',
    '比较仅修围栏与围栏加边框一起处理，报价分清新木料长度、柱脚工作及花园恢复范围。'],
  ['Campsie','2194','S09',
    'For a cupboard door dropping at one corner, show the open hinge and the board where its screws attach, alongside a closed-door view.', '柜门一角下垂，请提供开启的铰链、螺丝固定板材，以及柜门闭合状态的照片。',
    'Is the problem the hinge, its fixing holes or the cabinet panel?', '问题在铰链、固定孔，还是柜体板材？',
    'Record which hinge moves and whether screws have pulled out of the board. A compatible new hinge will not hold if the fixing material is damaged. Include door size and visible hardware markings. Avoid removing nearby appliances; the cabinet repair should be scoped independently of plumbing or electrical work.',
    '说明哪处铰链移动，以及螺丝是否从板材孔位脱出。固定基层破损时，即使新铰链相容也未必能牢固安装。请附门板尺寸与可见五金标记，不要为拍照拆开附近电器；柜体维修应与水管、电气工作分开，再决定调整、修孔还是换件。',
    'Compare hinge adjustment, compatible replacement and fixing-point repair. Confirm alignment of neighbouring doors after the work rather than judging success only by a new hinge being fitted.',
    '比较铰链调整、相容换件及固定点修复，确认施工后相邻柜门的对位，而不只看有没有装上新铰链。'],
  ['Fairy Meadow','2519','S07',
    'For a deck edge beside stairs or a timber screen, identify whether movement is in the deck board, the step or the screening.', 'Deck 边缘连着楼梯或木围板时，请说明移动的是面板、台阶，还是遮挡木条。',
    'Which part moves when the deck edge is used?', 'Deck 边缘究竟哪部分在移动？',
    'Describe the movement without walking on a suspect section to demonstrate it. Safe photos of the board ends, visible support and stair junction help separate surface repairs from support work. If screening must be removed for access, include its reinstatement and any finish matching in the scope.',
    '描述晃动情况即可，不要踩上疑似不稳部分演示。安全拍摄板端、可见支撑和楼梯接合处，有助于区分表面换板与支撑工作。如果为施工需要先拆围板，应把重新装回及表面匹配列入范围，避免面板修好后仍留下未收尾的开口。',
    'Compare isolated deck-board replacement with repairs to the adjoining edge. Price screen removal and refitting separately if it is needed to reach the affected timber.',
    '比较单块换板与相连边缘维修；如需拆围板才能处理木材，应另外列拆卸和装回费用。'],
  ['Gwynneville','2500','S02',
    'If you want to keep an existing door leaf, photograph the damaged jamb, hinge recesses and closed gaps before asking for a new frame.', '希望保留现有门板时，请先拍受损门框侧边、铰链槽及关闭缝隙，再讨论更换门框。',
    'Can sound parts of the doorway stay in place?', '门口完好的部件能否保留？',
    'Separate damage to the jamb, architrave and door leaf. A short trim repair differs from replacing timber that carries hinges. Say whether the door needs to remain usable during work. The quote should identify retained components and how the repaired frame will be aligned, sealed and finished.',
    '门框侧边、门套线和门板损坏要分别说明。补一段装饰线，与更换承托铰链的木材并不相同；也请告知施工期间是否要保持门能使用。报价应写明保留哪些部件，修好的门框怎样对位、封闭和表面收尾，而不笼统地只列“修门”。',
    'Compare a local timber repair with replacement of the affected jamb. Include removing and refitting the retained leaf, compatible hardware and making good around the trim.',
    '比较局部修木与更换受损框边，明确原门板拆装、相容五金及门套周围修整范围。'],
  ['Haymarket','2000','S08',
    'For interior trim or shelving in a managed building, send the room measurements and confirm how timber can reach the work area.', '管理建筑内做装饰线或层板，请提供房间尺寸，并说明木材怎样运到工作位置。',
    'How will materials reach the room without damaging shared areas?', '材料怎样进入房间，同时保护共用区域？',
    'If your building has a loading bay, lift booking or permitted work hours, include the arrangements that actually apply. Measure long trim runs and shelf openings before delivery is planned. Confirm the fixing surface, furniture clearance and whether wall patching or painting should be part of the quote.',
    '如你的建筑有装卸区、电梯预约或施工时间要求，请提供实际适用的安排，不必猜测。先量较长装饰线及层板开口，再安排搬运；也要确认固定基层、家具能否移开，以及是否需要墙面修补或刷漆，让材料进场与室内收尾都能按同一范围沟通。',
    'Compare a repair to the existing trim with replacement of one continuous run. Keep building access arrangements and room protection separate from material quantities.',
    '比较修补现有装饰线与更换一整段，建筑通道安排和室内保护应与材料数量分别说明。'],
  ['Killarney Vale','2261','S06',
    'A dragging gate and an adjoining leaning fence may share one support problem. Show the hinge post and the connected fence rails together.', '闸门刮地与相连围栏倾斜，可能涉及同一个支撑问题，请把铰链柱与相连横梁一起拍下。',
    'Does the gate need adjustment or does the supporting post move?', '应调整门扇，还是先处理会动的门柱？',
    'Explain whether the gap changes as the gate opens and whether the post moves with it. Do not force the gate to test it. Check photos should include the leaf joints, hinge attachment and adjoining rails. Confirm whether access through this entrance must remain available while repairs are arranged.',
    '说明开门时缝隙是否变化、门柱是否跟着移动，不要强推测试。照片应包含门扇接合处、铰链固定处及相连横梁；同时说明维修期间是否仍需使用这条通道。若根源在门柱，仅调整门闩可能不能解决，报价应先区分支撑与五金工作。',
    'Compare hinge and latch adjustment with post repair and gate rehanging. Include fence-rail connections where the same post supports both structures.',
    '比较铰链门闩调整与修柱后重新挂门；同一柱支撑围栏时，还要列出横梁连接工作。'],
  ['Kingsford','2032','S01',
    'For peeling window paint, include the sill ends and frame joints so coating wear can be separated from damaged timber.', '木窗掉漆请连同窗台端部和框接缝一起拍，便于区分涂层磨损与木材损坏。',
    'Is repainting enough, or does the timber need repair first?', '只需重刷，还是先修木材？',
    'Say whether the timber feels soft, the sash catches or the issue is limited to the coating. Photograph only safely accessible faces. External access and glazing may need separate arrangements. A useful quote distinguishes timber repair, preparation, sealing and final coating so a new finish does not conceal unresolved decay.',
    '说明是否有木材发软、窗扇卡住，或只是漆面磨损，只拍安全可及的位置。窗外通道及玻璃可能需要另行安排；报价应区分修木、前处理、封闭与最后涂层，避免新漆掩盖尚未处理的腐烂，也不要把表面翻新误当成开合机构已经修好。',
    'Compare coating-only preparation with timber repair followed by finishing. Ask which window faces are included and how the edge beside existing paint will be treated.',
    '比较仅处理涂层与先修木再收尾，确认包含窗户哪些面，以及新旧漆边缘如何过渡。'],
  ['Marsfield','2122','S17',
    'For timber screening beneath a house or deck, mark the opening you want covered and any access points that must remain usable.', '屋下或 Deck 下方做木围板，请标出希望遮挡的开口及必须保留的进入位置。',
    'Where should a removable screening section be placed?', '可拆检修围板应放在哪里？',
    'Show service access points, existing supports and the ground beneath the opening. Batten spacing and removable sections should be agreed before the screen is set out. The screen is a finish rather than structural support, and must not hide damaged framing or prevent necessary inspection and ventilation.',
    '请拍设备检修位置、现有支撑与开口下方地面，排板前先确认木条间距和可拆段位置。遮挡围板属于收尾，不代替承重支撑；不应把破损骨架遮住，也要保留需要的检查与通风。报价时把旧板拆卸、固定基层与表面处理分别列明。',
    'Compare replacing damaged battens with screening the whole opening. Include removable access, support preparation and an optional coating as separate decisions.',
    '比较更换坏木条与整段开口做围板，分别确定可拆通道、固定基层准备及是否加做涂层。'],
  ['Mount Ousley','2519','S17',
    'Where an outdoor screen meets uneven ground or stairs, show the complete bottom line instead of measuring only the tallest opening.', '户外围板连着不平地面或楼梯时，请拍完整底边走向，不只量最高的一处开口。',
    'How should screening follow the ground while keeping access?', '围板怎样随地面收边，同时保留通道？',
    'Record the height at both ends and where steps change the opening. Discuss stepped or cut-to-line battens and which edges will be sealed after cutting. The layout must still allow appropriate ground clearance, drainage and inspection access. Ask whether the proposed work affects a nearby gate or barrier before fixing the design.',
    '记录两端高度以及台阶改变开口的位置，讨论阶梯式排板或随线切割，并确认切口如何封闭。布局仍需考虑与地面的间隙、排水和检查通道；设计前也要说明是否靠近闸门或围栏，避免装上新木条后影响原有开合或其他必要功能。',
    'Compare keeping the existing straight top line with revising the lower batten lengths. The quote should show the corner returns and treatment of cut ends.',
    '比较保留原有平直顶边与调整下方木条长度，报价列出转角收边及切口处理。'],
  ['North Wollongong','2500','S01',
    'If a window repair needs both indoor and outdoor access, provide the floor level and the safe working positions available on each side.', '木窗维修涉及室内外两侧时，请提供楼层，以及各侧现有的安全施工位置。',
    'What can be assessed from inside and what needs external access?', '室内能检查哪些部分，哪些需要外侧通道？',
    'An indoor close-up can show a frame joint but may not reveal the outside sill or coating. Include a safe wider photo and any building-manager arrangements that apply. Timber work, glass replacement and external access equipment should be identified separately before a site visit and written quote are agreed.',
    '室内近照能显示框角，却未必看得到外侧窗台或涂层。请附安全拍摄的全景及实际适用的物业安排；修木、换玻璃与外侧施工设备要分别说明，再讨论现场查看和书面报价。不要为补拍照片探身窗外，缺少的视角可以留待安全检查。',
    'Compare a repair confined to accessible timber with a scope that needs external equipment. Confirm who arranges access and whether finishing covers both faces.',
    '比较仅处理可及木材与需要外侧设备的范围，确认谁安排通道，以及收尾是否包含两面。'],
  ['Rhodes','2138','S09',
    'For a cabinet door beside an appliance, show the door swing, nearby clearances and accessible hinge markings without moving the appliance.', '电器旁柜门维修，请拍开门方向、周边间隙及可见铰链标记，不要自行搬动电器。',
    'Can the cabinet hardware be replaced within the existing clearance?', '现有间隙能否容纳替换后的柜门五金？',
    'The hinge type, opening angle and mounting plate all affect compatibility. Explain whether the door catches the adjoining panel or appliance. Keep cabinet adjustment separate from disconnecting appliances or services. If the fixing board is swollen or broken, ask for that repair to be assessed before replacement hardware is selected.',
    '铰链类型、开启角度及底座都会影响相容性，请说明门是否碰到旁边板件或电器。柜门调整与拆接电器或管线不同，不应混入同一默认范围。固定板材如有膨胀或破裂，应先评估基层，再选替换五金，避免装上新配件仍无法正常开合。',
    'Compare a compatible hinge replacement with adjustment of the retained hardware. Include door clearance checks and fixing-board repair where required.',
    '比较相容换铰链与调整原有五金，必要时包含固定板修复，并核对最终开门间隙。'],
  ['Shellharbour','2529','S07',
    'Before refinishing a deck, separate loose fixings, split boards and soft timber from faded colour or worn coating.', 'Deck 翻新前，请先把固定件松动、板材开裂或发软，与褪色及涂层磨损分开。',
    'Which deck repairs should happen before a new finish?', '重新做表面涂层前，应先修哪些 Deck 问题？',
    'List each affected section and show board ends and visible fixings from a safe position. A new coating does not restore a weak board or support. Ask whether the quote covers isolated replacements, the retained boards and preparation across the chosen section. Final colour may vary between new and aged timber.',
    '逐段列出问题，并从安全位置拍板端与可见固定件。新涂层不能恢复坏板或支撑的强度；应明确报价包含局部换板、保留板材怎样处理，以及指定范围的前处理。新旧木材最后颜色可能不同，是否扩大收尾范围要先讨论，不要施工后才决定。',
    'Compare repair-only work with repair plus preparation and coating. Keep the quantity of new boards visible in both options rather than hiding replacement costs in a finish allowance.',
    '比较只维修与维修加前处理、涂层，两种方案都写清新板数量，不把换板费用混在表面处理里。'],
  ['Strathfield','2135','S01',
    'For more than one affected timber window or door, label photos by room and component so each repair can be considered separately.', '多扇木窗或木门有问题时，请按房间和构件标记照片，方便逐项评估。',
    'How do you compare several small timber repairs fairly?', '多项小木作维修，怎样比较报价才清楚？',
    'Use one overview per opening and a close-up for each different fault. Distinguish a soft sill, a rubbing door and damaged trim rather than grouping them as general carpentry. List the rooms that must remain usable and any furniture protection needed. Each item should identify repair, replacement and finishing separately.',
    '每个开口提供一张全景，每类问题再附近照。窗台发软、门刮擦及装饰线损坏要分开，不只写笼统的木工维修；注明哪些房间施工时仍需使用，以及家具保护要求。每项分别列维修、更换和表面收尾，才能按相同范围比较或分阶段安排。',
    'Ask for essential repairs and optional matching finishes as separate items. A combined visit can still retain a clear price and scope for each window or doorway.',
    '必要维修与可选外观匹配分别列项；即使合并上门，每扇窗或门口仍应有清楚的范围。'],
  ['The Entrance','2261','S06',
    'If a timber entrance gate cannot latch reliably, explain how it is used and show the latch, hinge post and closed gaps.', '木入口闸门扣不牢，请说明日常使用方式，并拍门闩、铰链柱与关闭缝隙。',
    'What needs checking before replacing the gate latch?', '换闸门门闩前，应先检查什么？',
    'A latch may miss because the leaf has dropped or the supporting post has moved. Show the whole gate and both fixing sides. Mention whether another entry can be used during work. If the gate forms part of a pool barrier, say so at the start; ordinary garden-gate repairs do not establish pool-safety compliance.',
    '门闩扣不上，可能是门扇下垂或支撑柱移动，需要整扇门和两侧固定位置的照片。说明施工期间是否有其他入口可用；如果该门属于泳池安全围栏的一部分，必须一开始就说明，不能把普通花园木门维修当作已满足泳池安全要求。',
    'Compare alignment work before choosing new hardware. Include the timber around the latch plate and confirm the closing action after the gate is rehung.',
    '选择新五金前先比较对位调整，检查扣板周围木材，并确认重新挂门后的关闭动作。'],
  ['Ultimo','2007','S08',
    'For replacement shelving, include the clear opening, intended storage and visible supports, not just the length of a new board.', '更换层板请提供净开口、计划存放物品和可见支撑，不只报一块新板的长度。',
    'Does the shelf need a new board or a different support layout?', '层板需要换板，还是改变支撑方式？',
    'Explain what the shelf will hold and photograph its brackets and fixing surface. A thicker shelf alone may not solve weak wall fixings. Confirm whether drilling, trim removal or wall making-good is expected, and mention building access arrangements where applicable. Do not load a visibly loose shelf for testing.',
    '说明层板用途，并拍支架与固定基层。仅加厚木板未必能解决墙面固定不稳；先确认是否涉及钻孔、拆线条或墙面修整，如有建筑进出要求也请提供。不要在明显松动的层板上加重物测试，报价前应把支撑方案和表面收尾一起沟通。',
    'Compare retaining sound supports with a revised support arrangement. Include shelf material, fixings and making-good rather than comparing board prices alone.',
    '比较保留完好支撑与重排支撑位置，报价包含板材、固定件及修整，而不只比较木板单价。'],
  ['Waterloo','2017','S02',
    'If a door catches after flooring work, show the floor transition and both hinge-side and latch-side gaps before deciding to trim it.', '换地板后门刮地，请先拍地面交接及铰链侧、锁舌侧缝隙，再决定是否修短。',
    'Has the floor height changed, or has the door dropped?', '是地面高度改变，还是门扇下垂？',
    'Say when the rubbing began and whether it affects the whole swing or one spot. Hinge movement, a high floor transition and a swollen lower edge need different solutions. Explain any special door identification before work is quoted; trimming an ordinary timber door must not be assumed suitable for a fire or other rated door.',
    '说明何时开始刮擦，是整个开门过程还是某一点发生。铰链移动、地面交接偏高及门底膨胀，需要不同处理。报价前请说明门上可见的特殊标识，不能把普通木门修边做法直接用于防火或其他有特定性能要求的门，再确认合适工种及方法。',
    'Compare adjustment with trimming only after the cause is identified. If trimming is suitable, include cut-edge sealing and a check of the latch and final clearances.',
    '确认原因后再比较调整与修边；如适合切边，包含切口封闭，并核对门闩和最终间隙。'],
  ['Wollongong','2500','S05',
    'For fence maintenance with other outdoor timber jobs, list the fence, gate, deck and garden edging as separate items in one enquiry.', '围栏保养连同其他户外木作询价时，请把围栏、闸门、Deck 和花园边框分别列项。',
    'Which outdoor jobs can share an assessment without blurring the scope?', '哪些户外工作可以一起查看，又不混淆范围？',
    'Provide an overview of the yard and label the affected components. Distinguish loose palings, gate alignment, deck boards and sleepers retaining soil. Note access for materials and any section that should not be used. Confirm appointment availability and the inclusions for each job before coordinating the work.',
    '提供庭院全景并标出受影响构件，分别说明松动围栏板、闸门对位、Deck 木板和涉及挡土的 sleeper。注明材料通道及不宜继续使用的区域；协调施工前，先确认可安排时间和每项包含的内容，避免“户外维修”一个总称掩盖支撑、排水或收尾差别。',
    'Compare essential stabilisation and timber replacement with optional finishing. Each component should keep its own scope even when quoted as a combined project.',
    '比较必要的稳固处理、换木材与可选表面收尾，即使合并成一个项目，每个构件仍保留独立范围。'],
  ['Zetland','2017','S08',
    'For skirting or architraves after another repair, photograph the unfinished junctions and the profile of the timber you want matched.', '其他维修后补踢脚线或门套线，请拍未收口接缝及希望匹配的原木条线型。',
    'Should a small trim gap be patched or a continuous length replaced?', '装饰线小缺口适合补一段，还是换连续整段？',
    'Measure between corners and show an undamaged section alongside the gap. Matching depends on the profile, thickness and available material. Explain whether adjoining walls and flooring are already finished so protection and touch-ups are included. Agree where a new length will stop before removal begins.',
    '量转角之间长度，并把完好线条和缺口一起拍下。能否匹配取决于线型、厚度及可采购材料；请说明相邻墙面与地板是否已完成，便于列出保护和补色。拆除前先确定新木条从哪里开始、在哪里结束，避免小补段最后变成范围不清的整面收尾。',
    'Compare a close profile match with replacement to the next natural corner. List caulking, nail-hole filling and paint touch-ups explicitly if they are required.',
    '比较接近原线型的局部匹配与更换到下一个自然转角；需要的填缝、钉孔修补及补漆明确列出。'],
];

export const addedAreaProfiles = Object.fromEntries(rows.map(([name, postcode, service, en, zh, questionEn, questionZh, detailEn, detailZh, optionEn, optionZh]) => [name, {
  name, postcode, service, en, zh, detail: { questionEn, questionZh, en: detailEn, zh: detailZh }, options: {en:optionEn,zh:optionZh},
}]));

// The nine existing owners retain their URLs, titles and detailed repair guidance.
const existing = [
  ['Ashfield','2131','S01','For window or door timber beside a balcony opening, show the junction with the surrounding wall. Separate moisture-source investigation from replacement timber and finishing.','阳台开口旁的门窗木材，需拍与周围墙面的接合处；受潮来源检查、换木材及表面收尾应分开。'],
  ['Burwood','2134','S09','If several cupboard doors need attention, label each one and keep hinge, runner and damaged-panel photos together. Confirm material matching before agreeing to replace a whole set.','多扇柜门需处理时逐一编号，把铰链、导轨及坏板照片按位置归组；先确认材料匹配，再决定是否整组更换。'],
  ['Chatswood','2067','S01','For a managed property, confirm who can arrange access and approve the timber scope. Provide window, door and cabinet photos separately so the right repair is discussed before a visit.','管理物业先确认谁安排进入并确认木作范围。木窗、门和柜体分开拍，便于上门前先讨论正确维修项目。'],
  ['Eastwood','2122','S02','If an indoor door and outdoor gate both catch, describe them separately: floor clearance and hinge adjustment differ from moving posts or weathered gate timber.','室内门与户外闸门都卡住时分开说明：地面间隙、铰链调整，与门柱移动、户外木材老化不同。'],
  ['Epping','2121','S01','When a sill end is soft, include the corner joint and adjacent painted timber. Ask what will be retained and how the new timber and coating meet the old frame.','窗台端部发软时，连同框角和相邻漆面木材一起拍；确认保留哪些部分，以及新木材、涂层与旧框怎样衔接。'],
  ['Hurstville','2220','S01','For window-frame maintenance, identify whether the priority is opening, decayed timber or the finish. Include safe access and any building work-hour restrictions that apply.','木窗框保养先说明重点是开合、腐木还是表面外观，并提供安全进入方式及实际适用的建筑施工时段。'],
  ['Parramatta','2150','S02','If a doorway is used throughout the day, explain which access must stay available. Separate repairs needed to restore closing from optional paint and trim matching.','门口白天持续使用时，请说明必须保留哪条通道；恢复开关所需维修，与可选刷漆及门套匹配分开列项。'],
  ['Ryde','2112','S05','For a fence, gate and sleeper edge along the same boundary, show the full run. Mark which supports move and which timber you want to keep before comparing repairs with replacement.','同一边界有围栏、闸门和 sleeper 边框时拍整排，标出移动的支撑与希望保留的木材，再比较维修和更换。'],
  ['Sydney CBD','2000','S08','For Sydney City enquiries, include the floor, work area and any lift or loading bookings. Cabinet repairs, internal trim and timber-door work can be listed separately in one request.','Sydney City 市区询价请说明楼层、工作位置及电梯或装卸预约。柜体、室内线条和木门工作可以在同一询价中分别列明。'],
];
export const popularAreaProfiles = {
  ...Object.fromEntries(existing.map(([name,postcode,service,en,zh])=>[name,{name,postcode,service,en,zh}])),
  ...addedAreaProfiles,
};
